### PR TITLE
Optimize host function call

### PR DESCRIPTION
**Pull request by arkpar**
This small optimization give +10% block import speed for substrate

### CODE REVIEW

**Comment by NikVolf** [comment]
Why not just `SmallVec`?

**Comment by arkpar** [comment]
Don't want to introduce extra dependencies to save a few lines of code

**Comment by NikVolf** [comment]
It is not very nice code without it, and smallvec is already in the dependency tree :)

**Comment by arkpar** [comment]
It is not a dependency of this crate. I think it has higher chance of being included upstream without introducing a new dependency.
Also, this is performance critical part of the code, so I'd prefer explicit efficiency over code niceness here.

**Pull request merged**
